### ISSUE TITLE
Where/How do I type in the commands?

### ISSUE THREAD

**Issue by maddoxrj** [WeatherElectric/CompanyExecutive#1]
I've downloaded the mod but i can't seem to find out where or how to use the commands.

**Comment by FragileDeviations** [comment]
what?
there are no commands lol

**Comment by JackMidnightVR** [comment]
> what? there are no commands lol

so it does not work? cause theres no config for the mod neither anything to use ingame

**Comment by FragileDeviations** [comment]
...it's in the preferences file
![5etp7](https://github.com/WeatherElectric/CompanyExecutive/assets/30084485/1a5ce588-1ee8-4b75-9923-9b047b8ec792)
