### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by JackMidnightVR** [WeatherElectric/CompanyExecutive#2]
it does not create a config file neither does it change anything ingame im starting with basic 60 bucks and loading into a mission changes nothing

**Comment by FragileDeviations** [comment]
then you didn't install it right because it's working fine for me with both bepin ML compatibility and ML itself

**Comment by JackMidnightVR** [comment]
i installed it via r2modman

**Comment by FragileDeviations** [comment]
you're doing it wrong, because it works fine.
